export const MVP_ERROR_CODES = [
  'VALIDATION_ERROR',
  'AUTH_REQUIRED',
  'AUTH_INVALID_CREDENTIALS',
  'INTERNAL_TOKEN_INVALID',
  'ACCESS_DENIED',
  'CSRF_INVALID',
  'RESOURCE_NOT_FOUND',
  'USER_ALREADY_EXISTS',
  'CONVERSATION_BUSY',
  'DUPLICATE_REQUEST',
  'MESSAGE_STATE_CONFLICT',
  'SNAPSHOT_TOO_LARGE',
  'AGENT_DOWNSTREAM_ERROR',
  'AGENT_NO_FINAL_EVENT',
  'INTERNAL_ERROR',
  'DATABASE_UNAVAILABLE',
  'CLIENT_DISCONNECTED',
  'SERVICE_RESTARTED',
  'AGENT_STREAM_INTERRUPTED',
  'SNAPSHOT_INVALID',
] as const;

export type MvpErrorCode = (typeof MVP_ERROR_CODES)[number];
