package com.jd.genie.platform.phase2.tooling;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.jd.genie.platform.contract.CurrentUserProvider;
import com.jd.genie.platform.contract.MvpErrorCode;
import com.jd.genie.platform.phase2contract.error.Phase2ContractException;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.LocalDateTime;
import java.util.HexFormat;
import java.util.List;
import java.util.UUID;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import java.security.MessageDigest;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class McpServerService {
    private final JdbcTemplate jdbc; private final CurrentUserProvider currentUser; private final CredentialEnvelopeService credentials;
    private final ObjectMapper objectMapper; private final Clock clock; private final McpClientAdapter client; private final McpUrlPolicy urlPolicy;
    public McpServerService(JdbcTemplate jdbc, CurrentUserProvider currentUser, CredentialEnvelopeService credentials, ObjectMapper objectMapper, Clock clock, McpClientAdapter client, McpUrlPolicy urlPolicy) {
        this.jdbc = jdbc; this.currentUser = currentUser; this.credentials = credentials; this.objectMapper = objectMapper; this.clock = clock; this.client=client; this.urlPolicy=urlPolicy;
    }
    public List<McpServerResponse> list() { var u=currentUser.requireCurrentUser(); return jdbc.query("SELECT * FROM mcp_server WHERE tenant_id=? AND owner_id=? AND deleted_at IS NULL ORDER BY created_at DESC", this::server, u.tenantId(), u.userId()); }
    public McpServerResponse get(String id) { var u=currentUser.requireCurrentUser(); return one(u.tenantId(),u.userId(),id); }
    @Transactional public McpServerResponse create(CreateMcpServerRequest req) {
        validate(req); urlPolicy.validate(req.serverUrl()); var u=currentUser.requireCurrentUser(); String id=UUID.randomUUID().toString(); LocalDateTime now=LocalDateTime.now(clock);
        String envelope=credentials.encrypt(req.credential(),u.tenantId(),u.userId(),id,req.authType());
        try { jdbc.update("INSERT INTO mcp_server(id,tenant_id,owner_id,name,server_url,auth_type,auth_name,credential_envelope,status,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,'DRAFT',0,?,?)", id,u.tenantId(),u.userId(),req.name().trim(),req.serverUrl().trim(),req.authType().name(),blankToNull(req.authName()),envelope,now,now); }
        catch (DataAccessException ex) { throw new Phase2ContractException(MvpErrorCode.VALIDATION_ERROR,"MCP server cannot be saved",ex); }
        return one(u.tenantId(),u.userId(),id);
    }
    @Transactional public McpServerResponse update(String id, UpdateMcpServerRequest req) {
        if(req==null || req.version()<0) throw validation(); validate(req.name(),req.serverUrl(),req.authType(),req.authName()); urlPolicy.validate(req.serverUrl()); var u=currentUser.requireCurrentUser(); var existing=raw(u.tenantId(),u.userId(),id); LocalDateTime now=LocalDateTime.now(clock);
        String envelope=existing.credentialEnvelope; if(Boolean.TRUE.equals(req.clearCredential())) envelope=null; else if(req.credential()!=null && !req.credential().isBlank()) envelope=credentials.encrypt(req.credential(),u.tenantId(),u.userId(),id,req.authType());
        int changed=jdbc.update("UPDATE mcp_server SET name=?,server_url=?,auth_type=?,auth_name=?,credential_envelope=?,updated_at=?,version=version+1 WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL AND version=?",req.name().trim(),req.serverUrl().trim(),req.authType().name(),blankToNull(req.authName()),envelope,now,id,u.tenantId(),u.userId(),req.version());
        if(changed!=1) throw new Phase2ContractException(MvpErrorCode.VERSION_CONFLICT,"MCP server version conflict"); return one(u.tenantId(),u.userId(),id);
    }
    @Transactional public void delete(String id,long version) { var u=currentUser.requireCurrentUser(); raw(u.tenantId(),u.userId(),id); LocalDateTime now=LocalDateTime.now(clock); int changed=jdbc.update("UPDATE mcp_server SET status='DISABLED',deleted_at=?,updated_at=?,version=version+1 WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL AND version=?",now,now,id,u.tenantId(),u.userId(),version); if(changed!=1) throw new Phase2ContractException(MvpErrorCode.VERSION_CONFLICT,"MCP server version conflict"); jdbc.update("UPDATE mcp_tool SET available=FALSE,updated_at=?,version=version+1 WHERE mcp_server_id=? AND tenant_id=? AND owner_id=?",now,id,u.tenantId(),u.userId()); }
    @Transactional public McpServerResponse setStatus(String id,long version,McpServerStatus status) { var u=currentUser.requireCurrentUser(); var s=raw(u.tenantId(),u.userId(),id); if(status==McpServerStatus.ENABLED){long available=jdbc.queryForObject("SELECT COUNT(*) FROM mcp_tool WHERE mcp_server_id=? AND tenant_id=? AND owner_id=? AND available=TRUE",Long.class,id,u.tenantId(),u.userId()); if(!"SUCCESS".equals(s.lastCheckStatus) || available<1) throw new Phase2ContractException(MvpErrorCode.MCP_UNAVAILABLE,"MCP server has not passed a tool check"); } LocalDateTime now=LocalDateTime.now(clock); int changed=jdbc.update("UPDATE mcp_server SET status=?,updated_at=?,version=version+1 WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL AND version=?",status.name(),now,id,u.tenantId(),u.userId(),version); if(changed!=1) throw new Phase2ContractException(MvpErrorCode.VERSION_CONFLICT,"MCP server version conflict"); return one(u.tenantId(),u.userId(),id); }
    @Transactional public McpServerResponse test(String id) { var u=currentUser.requireCurrentUser(); Raw s=raw(u.tenantId(),u.userId(),id); String url=jdbc.queryForObject("SELECT server_url FROM mcp_server WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",String.class,id,u.tenantId(),u.userId()); String status="SUCCESS", code=null; try { client.listTools(url,AuthType.valueOf(s.authType),s.authName,credentials.decrypt(s.credentialEnvelope,u.tenantId(),u.userId(),id,AuthType.valueOf(s.authType))); } catch(Phase2ContractException ex){ status="FAILED"; code=ex.errorCode().name(); } LocalDateTime now=LocalDateTime.now(clock); jdbc.update("UPDATE mcp_server SET last_check_status=?,last_check_code=?,last_checked_at=?,updated_at=? WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",status,code,now,now,id,u.tenantId(),u.userId()); return one(u.tenantId(),u.userId(),id); }
    @Transactional(noRollbackFor = Phase2ContractException.class) public List<McpToolResponse> refreshTools(String id) {
        var u=currentUser.requireCurrentUser(); Raw s=raw(u.tenantId(),u.userId(),id); String url=jdbc.queryForObject("SELECT server_url FROM mcp_server WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",String.class,id,u.tenantId(),u.userId());
        List<McpClientAdapter.RemoteTool> remote;
        try { remote=client.listTools(url,AuthType.valueOf(s.authType),s.authName,credentials.decrypt(s.credentialEnvelope,u.tenantId(),u.userId(),id,AuthType.valueOf(s.authType))); } catch (Phase2ContractException ex) { markCheck(u.tenantId(),u.userId(),id,"FAILED",ex.errorCode().name()); throw ex; }
        if(remote==null||remote.size()>200) throw discoveryInvalid(); Set<String> names=new HashSet<>(); List<String> runtimeNames=new ArrayList<>(); for(var tool:remote){ if(tool==null||tool.name()==null||tool.name().isBlank()||!names.add(tool.name())||tool.inputSchema()==null||!tool.inputSchema().isObject()||tool.inputSchema().toString().length()>256*1024) throw discoveryInvalid(); runtimeNames.add(runtimeName(id,tool.name(),runtimeNames)); }
        LocalDateTime now=LocalDateTime.now(clock); for(int i=0;i<remote.size();i++){var t=remote.get(i);String schema;try{schema=objectMapper.writeValueAsString(t.inputSchema());}catch(Exception e){throw discoveryInvalid();}String hash=sha256(schema);int changed=jdbc.update("UPDATE mcp_tool SET runtime_name=?,description=?,input_schema=?,schema_hash=?,available=TRUE,discovered_at=?,updated_at=?,version=version+1 WHERE mcp_server_id=? AND tenant_id=? AND owner_id=? AND tool_name=?",runtimeNames.get(i),t.description(),schema,hash,now,now,id,u.tenantId(),u.userId(),t.name());if(changed==0)jdbc.update("INSERT INTO mcp_tool(id,tenant_id,owner_id,mcp_server_id,tool_name,runtime_name,description,input_schema,schema_hash,enabled,available,version,discovered_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,TRUE,TRUE,0,?,?)",UUID.randomUUID().toString(),u.tenantId(),u.userId(),id,t.name(),runtimeNames.get(i),t.description(),schema,hash,now,now);}
        if (remote.isEmpty()) jdbc.update("UPDATE mcp_tool SET available=FALSE,updated_at=?,version=version+1 WHERE mcp_server_id=? AND tenant_id=? AND owner_id=?",now,id,u.tenantId(),u.userId()); else jdbc.update("UPDATE mcp_tool SET available=FALSE,updated_at=?,version=version+1 WHERE mcp_server_id=? AND tenant_id=? AND owner_id=? AND tool_name NOT IN ("+String.join(",",java.util.Collections.nCopies(remote.size(),"?"))+")",concat(now,id,u.tenantId(),u.userId(),names.toArray())); markCheck(u.tenantId(),u.userId(),id,"SUCCESS",null); return tools(id);
    }
    public List<McpToolResponse> tools(String id) { var u=currentUser.requireCurrentUser(); one(u.tenantId(),u.userId(),id); return jdbc.query("SELECT id,tool_name,runtime_name,description,input_schema,enabled,available,version FROM mcp_tool WHERE mcp_server_id=? AND tenant_id=? AND owner_id=? ORDER BY tool_name",(rs,n)->tool(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),parse(rs.getString(5)),rs.getBoolean(6),rs.getBoolean(7),rs.getLong(8)),id,u.tenantId(),u.userId()); }
    public List<McpToolResponse> capabilities() { var u=currentUser.requireCurrentUser(); return jdbc.query("SELECT id,tool_name,runtime_name,description,input_schema,enabled,available,version FROM mcp_tool WHERE tenant_id=? AND owner_id=? AND enabled=TRUE AND available=TRUE ORDER BY runtime_name",(rs,n)->tool(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),parse(rs.getString(5)),rs.getBoolean(6),rs.getBoolean(7),rs.getLong(8)),u.tenantId(),u.userId()); }
    @Transactional public McpToolResponse setToolEnabled(String serverId,String toolId,UpdateToolEnabledRequest req){if(req==null||req.enabled()==null)throw validation();var u=currentUser.requireCurrentUser();one(u.tenantId(),u.userId(),serverId);int c=jdbc.update("UPDATE mcp_tool SET enabled=?,updated_at=?,version=version+1 WHERE id=? AND mcp_server_id=? AND tenant_id=? AND owner_id=? AND version=?",req.enabled(),LocalDateTime.now(clock),toolId,serverId,u.tenantId(),u.userId(),req.version());if(c!=1)throw new Phase2ContractException(MvpErrorCode.VERSION_CONFLICT,"Tool version conflict");return tools(serverId).stream().filter(t->t.id().equals(toolId)).findFirst().orElseThrow(()->notFound());}
    private McpServerResponse one(String tenant,String owner,String id){try{return jdbc.queryForObject("SELECT * FROM mcp_server WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",this::server,id,tenant,owner);}catch(Exception e){throw notFound();}}
    private Raw raw(String tenant,String owner,String id){try{return jdbc.queryForObject("SELECT credential_envelope,last_check_status,auth_type,auth_name FROM mcp_server WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",(rs,n)->new Raw(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)),id,tenant,owner);}catch(Exception e){throw notFound();}}
    private McpServerResponse server(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new McpServerResponse(rs.getString("id"),rs.getString("name"),rs.getString("server_url"),AuthType.valueOf(rs.getString("auth_type")),rs.getString("auth_name"),McpServerStatus.valueOf(rs.getString("status")),rs.getString("credential_envelope")!=null,rs.getString("last_check_status"),rs.getString("last_check_code"),rs.getTimestamp("last_checked_at")==null?null:rs.getTimestamp("last_checked_at").toLocalDateTime(),rs.getLong("version"),rs.getTimestamp("created_at").toLocalDateTime(),rs.getTimestamp("updated_at").toLocalDateTime());}
    private McpToolResponse tool(String id,String name,String runtime,String desc,JsonNode schema,boolean enabled,boolean available,long version){return new McpToolResponse(id,name,runtime,desc,schema,enabled,available,version);}
    private JsonNode parse(String s){try{return objectMapper.readTree(s);}catch(Exception e){return objectMapper.createObjectNode();}}
    private Object[] concat(Object... values){return values;}
    private void markCheck(String tenant,String owner,String id,String status,String code){jdbc.update("UPDATE mcp_server SET last_check_status=?,last_check_code=?,last_checked_at=?,updated_at=? WHERE id=? AND tenant_id=? AND owner_id=? AND deleted_at IS NULL",status,code,LocalDateTime.now(clock),LocalDateTime.now(clock),id,tenant,owner);}
    private Phase2ContractException discoveryInvalid(){return new Phase2ContractException(MvpErrorCode.MCP_DISCOVERY_INVALID,"MCP discovery response invalid");}
    private String runtimeName(String serverId,String name,List<String> used){String normalized=name.toLowerCase().replaceAll("[^a-z0-9]+","_").replaceAll("^_+|_+$","");if(normalized.isBlank())throw discoveryInvalid();String base="mcp_"+sha256(serverId).substring(0,12)+"_"+normalized;if(base.length()>320)base=base.substring(0,320);if(used.contains(base))base=base.substring(0,Math.min(311,base.length()))+"_"+sha256(name).substring(0,8);used.add(base);return base;}
    private String sha256(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private void validate(CreateMcpServerRequest r){if(r==null)throw validation();validate(r.name(),r.serverUrl(),r.authType(),r.authName());}
    private void validate(String name,String url,AuthType type,String authName){if(name==null||name.isBlank()||name.length()>128||url==null||url.isBlank()||url.length()>2048||type==null)throw validation();if(type==AuthType.QUERY_PARAM&&(authName==null||authName.isBlank()))throw validation();if(type==AuthType.NONE&&authName!=null&&!authName.isBlank())throw validation();}
    private String blankToNull(String v){return v==null||v.isBlank()?null:v.trim();} private Phase2ContractException validation(){return new Phase2ContractException(MvpErrorCode.VALIDATION_ERROR,"Invalid MCP server request");} private Phase2ContractException notFound(){return new Phase2ContractException(MvpErrorCode.RESOURCE_NOT_FOUND,"Resource not found");}
    private record Raw(String credentialEnvelope,String lastCheckStatus,String authType,String authName){}
}
