package com.jd.genie.platform.phase2contract.enums;

public enum OrchestrationEventType {
    ROUTE_SELECTED,
    PLAN_CREATED,
    STEP_STARTED,
    STEP_COMPLETED,
    STEP_FAILED,
    STEP_SKIPPED,
    REPLAN_STARTED,
    SUMMARY_STARTED,
    SUMMARY_COMPLETED,
    SUMMARY_FALLBACK,
    FINAL_RESPONSE,
    PARALLEL_STARTED,
    SUBTASK_STARTED,
    SUBTASK_COMPLETED,
    SUBTASK_FAILED,
    STEP_REVIEW_STARTED,
    STEP_RETRY_STARTED,
    STEP_FALLBACK_STARTED,
    STEP_DEGRADED
}
